### Obtener todos los Pokemon
GET http://127.0.0.1:8000/pokemons
Accept: application/json

###

### Crear un Pokemon
POST http://127.0.0.1:8000/pokemons
Content-Type: application/json
Accept: application/json

{
  "nombre": "Pikachu",
  "imagen": "https://link_a_imagen_de_pikachu.jpg",
  "caracteristicas": {
    "peso": 6.0,
    "altura": 0.4,
    "fuerza": 55,
    "edad": 5
  },
  "habilidades": [
    "Impactrueno",
    "Cola ferrea"
  ],
  "tipo": "Electrico",
  "habitat": "Bosques"
}

###

### Obtener un Pokemon por ID
GET http://127.0.0.1:8000/pokemons/1
Accept: application/json

###

### Actualizar un Pokemon por ID
PUT http://127.0.0.1:8000/pokemons/1
Content-Type: application/json
Accept: application/json

{
  "nombre": "Pikachu",
  "imagen": "https://link_a_imagen_de_pikachu_actualizada.jpg",
  "caracteristicas": {
    "peso": 6.2,
    "altura": 0.4,
    "fuerza": 60,
    "edad": 6
  },
  "habilidades": [
    "Impactrueno",
    "Ataque rapido"
  ],
  "tipo": "Electrico",
  "habitat": "Bosques"
}

###

### Eliminar un Pokemon por ID
DELETE http://127.0.0.1:8000/pokemons/1
Accept: application/json

